name: Android CI Build

on:
  push:
    branches: [ "main", "master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          # The "cache: gradle" line has been removed to force a clean build.

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        id: setup_ndk
        with:
          ndk-version: r26b

      - name: Create local.properties
        run: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          echo "ndk.dir=${{ steps.setup_ndk.outputs.ndk-path }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        # We can remove --no-daemon now as the clean state will solve the issue.
        run: ./gradlew clean assembleDebug --rerun-tasks

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
